# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import nexus_cv_pb2 as nexus__cv__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in nexus_cv_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NexusCVServiceStub(object):
    """NexusCVService provides bidirectional streaming inference over gRPC.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamInference = channel.stream_stream(
                '/nexus_cv.NexusCVService/StreamInference',
                request_serializer=nexus__cv__pb2.InferenceRequest.SerializeToString,
                response_deserializer=nexus__cv__pb2.InferenceResponse.FromString,
                _registered_method=True)


class NexusCVServiceServicer(object):
    """NexusCVService provides bidirectional streaming inference over gRPC.
    """

    def StreamInference(self, request_iterator, context):
        """StreamInference accepts a stream of frame requests and returns
        a stream of inference responses in real time.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NexusCVServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamInference': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamInference,
                    request_deserializer=nexus__cv__pb2.InferenceRequest.FromString,
                    response_serializer=nexus__cv__pb2.InferenceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nexus_cv.NexusCVService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nexus_cv.NexusCVService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NexusCVService(object):
    """NexusCVService provides bidirectional streaming inference over gRPC.
    """

    @staticmethod
    def StreamInference(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/nexus_cv.NexusCVService/StreamInference',
            nexus__cv__pb2.InferenceRequest.SerializeToString,
            nexus__cv__pb2.InferenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
